In [2]:
#clonar pasta
!git clone https://github.com/ucfilho/ANN
% cd ANN
!ls

fatal: destination path 'ANN' already exists and is not an empty directory.
/content/ANN
ann_aula_ago_14_2018_leitura_git.ipynb
ANN_aula_Scikit_learn _ago_29_2018.ipynb
ANN_Hydrofoil_ago_29_2018.txt.ipynb
ANN_Hydrofoil_set_05_2018.ipynb
Aprendendo_Um_Pouco_mais_sobre_Python_set_05_2018.ipynb
arvore.jpg
Aula_003_Python_audio_e_imagem_ago_29_2018.ipynb
aula_04_rede_neural_set_05_2018.pdf
BBC_007041008.wav
Criando_Gethub_Ver_Youtube.txt
FAULT_DIAGNOSIS_maio_25_2017.txt
Hydrofoil_ago_29_2018.csv
john_mccarthy.png
Paper_Carvao_China_abril_12_2016.csv
Paper_Carvao_China_mar_31_2016.txt
README.md
simbolos.pdf
Video_mp4_Python_Notebook.ipynb


In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
#pegando dados da pasta
DAT=pd.read_csv("Hydrofoil_ago_29_2018.csv")
print(DAT.head())

   Unnamed: 0  Case  Hydrofoil    Froude  Resistence   Sinkage      Trim  \
0           1     1          1  0.000000    0.000000  0.000000  0.000000   
1           2     2          1  0.103733    2.549729 -0.689028  1.353022   
2           3     3          1  0.124480    3.628461 -0.835413  1.346323   
3           4     4          1  0.165973    6.374322 -1.864337  1.361538   
4           5     5          1  0.186719    8.217973 -2.301539  1.378858   

      Power  
0  0.000000  
1  0.950991  
2  1.624000  
3  3.803965  
4  5.517212  


In [5]:
#selecionando alguns dados de DAT
#os dados selecionados são as entradas e as saídas da rede
Index=[2,3,4,5,6,7]
DAT_select=[]
DAT_select=DAT.iloc[:,Index].copy()
print(DAT_select.head())

   Hydrofoil    Froude  Resistence   Sinkage      Trim     Power
0          1  0.000000    0.000000  0.000000  0.000000  0.000000
1          1  0.103733    2.549729 -0.689028  1.353022  0.950991
2          1  0.124480    3.628461 -0.835413  1.346323  1.624000
3          1  0.165973    6.374322 -1.864337  1.361538  3.803965
4          1  0.186719    8.217973 -2.301539  1.378858  5.517212


In [6]:
#normalizar os dados selecionados
def normalize(x):
  #pega o nome das colunas
  strings=list(x)
  for i in strings:
    #para cada coluna faz a normalização
    max_x=x[i].max()
    min_x=x[i].min()
    a=(max_x+min_x)/2
    b=(max_x-min_x)/2
    x[i]=(x[i]-a)/b
  return x
DAT_select_n=normalize(DAT_select)
print(DAT_select_n.head())

   Hydrofoil    Froude  Resistence   Sinkage      Trim     Power
0       -1.0 -1.000000   -1.000000 -0.883085 -1.000000 -1.000000
1       -1.0 -0.913570   -0.986458 -0.895478 -0.459481 -0.999415
2       -1.0 -0.896283   -0.980729 -0.898111 -0.462157 -0.999001
3       -1.0 -0.861711   -0.966146 -0.916618 -0.456079 -0.997659
4       -1.0 -0.844425   -0.956354 -0.924482 -0.449160 -0.996605


In [7]:
#pega aleatoriamente 80% dos dados para treinamento
#random_state=1 especifica a semente de aleatoriedade
train=DAT_select_n.sample(frac=0.8,random_state=1)
print(train.head())
#pega o restante dos dados para o teste
test=DAT_select_n.drop(train.index)
print(test.head())

    Hydrofoil    Froude  Resistence   Sinkage      Trim     Power
49   1.000000 -0.308557   -0.210937 -0.324422  0.618822 -0.727204
2   -1.000000 -0.896283   -0.980729 -0.898111 -0.462157 -0.999001
35   0.333333 -0.308557   -0.179688 -0.344609  0.660664 -0.716400
47   1.000000 -0.654278   -0.619792 -0.967466 -0.156350 -0.934277
39   0.333333  0.382887    0.187500  0.645534  0.601068 -0.178911
   Hydrofoil    Froude  Resistence   Sinkage      Trim     Power
0       -1.0 -1.000000   -1.000000 -0.883085 -1.000000 -1.000000
1       -1.0 -0.913570   -0.986458 -0.895478 -0.459481 -0.999415
5       -1.0 -0.827139   -0.944948 -0.910184 -0.453078 -0.995242
8       -1.0 -0.308557   -0.183333 -0.432939  0.709855 -0.717661
9       -1.0 -0.135696   -0.018750 -0.168314  0.796046 -0.575951


In [8]:
#pega dados de entrada da rede
#esses dados são necessários na etapa de treinamento e teste
Indice=[0,1]
train_x=[]
train_x=train.iloc[:,Indice].copy()
print(train_x.head())
test_x=[]
test_x=test.iloc[:,Indice].copy()
print(test_x.head())


    Hydrofoil    Froude
49   1.000000 -0.308557
2   -1.000000 -0.896283
35   0.333333 -0.308557
47   1.000000 -0.654278
39   0.333333  0.382887
   Hydrofoil    Froude
0       -1.0 -1.000000
1       -1.0 -0.913570
5       -1.0 -0.827139
8       -1.0 -0.308557
9       -1.0 -0.135696


In [9]:
#pega dados de saida da rede
#esses dados são necessários na etapa de treinamento e teste
Indice=[2,3,4,5]
train_y=[]
train_y=train.iloc[:,Indice].copy()
print(train_y.head())
test_y=[]
test_y=test.iloc[:,Indice].copy()
print(test_y.head())

    Resistence   Sinkage      Trim     Power
49   -0.210937 -0.324422  0.618822 -0.727204
2    -0.980729 -0.898111 -0.462157 -0.999001
35   -0.179688 -0.344609  0.660664 -0.716400
47   -0.619792 -0.967466 -0.156350 -0.934277
39    0.187500  0.645534  0.601068 -0.178911
   Resistence   Sinkage      Trim     Power
0   -1.000000 -0.883085 -1.000000 -1.000000
1   -0.986458 -0.895478 -0.459481 -0.999415
5   -0.944948 -0.910184 -0.453078 -0.995242
8   -0.183333 -0.432939  0.709855 -0.717661
9   -0.018750 -0.168314  0.796046 -0.575951


In [10]:
#chamando biblioteca para treinamento
from sklearn.neural_network import MLPRegressor
clf=MLPRegressor(solver='lbfgs',activation='tanh',alpha=1e-5,hidden_layer_sizes=(9,8),random_state=1)
clf.fit(train_x,train_y)


MLPRegressor(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(9, 8), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [11]:
#saidas preditas pela rede no treinamento e no teste
w_train=clf.predict(train_x)
w_test=clf.predict(test_x)
print(w_train)
print(w_test)
#transformando w_train em dataframe
w_train=pd.DataFrame(w_train)
#atribuindo a linha de nomes a w_train
col_names=list(train_y)
w_train.columns=col_names
print(w_train.head())
#transformando w_test em dataframe
w_test=pd.DataFrame(w_test)
col_names=list(train_y)
w_test.columns=col_names
print(w_test.head())

[[-0.15058868 -0.33115404  0.72860447 -0.72396226]
 [-0.96966957 -0.94509564 -0.55029266 -1.02136742]
 [-0.13380208 -0.37894814  0.71542808 -0.70419949]
 [-0.63642809 -0.87150792  0.01596687 -0.94601972]
 [ 0.19674006  0.63981424  0.49570646 -0.16017565]
 [-0.29123871 -0.71866652  0.59428047 -0.8201078 ]
 [ 0.06921829  0.48607716  0.52074366 -0.34276525]
 [-0.65161558 -0.8747864  -0.04052233 -0.92424865]
 [-0.12387373 -0.42379177  0.74565829 -0.6900679 ]
 [-0.00853852  0.58517919  0.49793499 -0.40920719]
 [ 0.73973281  0.84555847  0.24857169  0.62694673]
 [-0.94670023 -0.93978387 -0.49744247 -1.01436126]
 [-0.07924137 -0.01193303  0.61140305 -0.59381119]
 [ 0.36604059  0.74594633  0.43996013  0.08115483]
 [ 0.13177061  0.37403692  0.58408251 -0.2998542 ]
 [ 0.07028238  0.0643493   0.74161737 -0.43055591]
 [-0.0723421   0.36860624  0.54044039 -0.52556975]
 [ 0.46308564  0.64438146  0.55663903  0.14250888]
 [ 0.37731951  0.87048311  0.26488716  0.18991773]
 [ 1.03255169  0.80210287  0.33

In [12]:
#pegando dos dados originais das saídas da redes
DAT=pd.read_csv("Hydrofoil_ago_29_2018.csv")
DAT_select_sai=[]
Indice=[4,5,6,7]
DAT_select_sai=DAT.iloc[:,Indice].copy()
print(DAT_select_sai.head())


   Resistence   Sinkage      Trim     Power
0    0.000000  0.000000  0.000000  0.000000
1    2.549729 -0.689028  1.353022  0.950991
2    3.628461 -0.835413  1.346323  1.624000
3    6.374322 -1.864337  1.361538  3.803965
4    8.217973 -2.301539  1.378858  5.517212


In [13]:
#função para retornar os dados a escala original
def Original (x,x_old):
  strings=list(x)
  for i in strings: 
    max_x=x_old[i].max()
    min_x=x_old[i].min()
    a=(max_x+min_x)/2
    b=(max_x-min_x)/2
    x[i]=x[i]*b+a
  return x
w_train=Original(w_train,DAT_select_sai)
print(w_train.head())
w_test=Original(w_test,DAT_select_sai)
print(w_test.head())
test_y=Original(test_y,DAT_select_sai)
print(test_y.head())


   Resistence    Sinkage      Trim        Power
0  159.933688  30.685650  4.327027   448.576171
1    5.710846  -3.447602  1.125703   -34.723213
2  163.094398  28.028447  4.294044   480.691742
3   68.456112   0.643648  2.543159    87.720858
4  225.331410  84.668482  3.744039  1364.759737
   Resistence    Sinkage      Trim       Power
0   -1.899003  -4.130659  0.827318  -43.064850
1    3.923306  -3.581190  1.066605  -38.682006
2   15.466889  -2.814526  1.411715   -7.119776
3  166.943317  22.190620  4.652291  519.574158
4  184.981501  39.271515  4.496053  717.323126
   Resistence    Sinkage      Trim       Power
0    0.000000   0.000000  0.000000    0.000000
1    2.549729  -0.689028  1.353022    0.950991
5   10.365629  -1.506604  1.369050    7.732290
8  153.768272  25.026706  4.280094  458.816682
9  184.757286  39.739036  4.495847  689.102861
